name: Fetch Google Sheets Data

on:
  schedule:
    - cron: '0 * * * *'  # 每小時運行一次
  workflow_dispatch:  # 添加手動觸發功能

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 設置 Python 版本

      - name: Install pandas
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Fetch data from Google Sheets
        run: |
          curl -o data.csv "https://docs.google.com/spreadsheets/d/e/2PACX-1vRJ-iEq5K4CUbqtA6N21WDY8r_Fqk3Kvnw2Ks9l0jr0g31tQxEj_p1g9a23ambhG9qBtRbh_GepgiI2/pub?gid=0&single=true&output=csv&range=A9:D16"
          # 將 CSV 轉換為 JSON
          python -c "
import pandas as pd
data = pd.read_csv('data.csv')
data.to_json('risk_age_group.json', orient='records', lines=True)
"
      
      - name: Upload JSON file
        uses: actions/upload-artifact@v2
        with:
          name: risk-age-group-json
          path: risk_age_group.json
