name: risk_age_group.json - Fetch Google Spreadsheet Data

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch: # 支持手動觸發

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install python3-pip
          pip3 install pandas

      - name: Fetch data from Google Sheets
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vRJ-iEq5K4CUbqtA6N21WDY8r_Fqk3Kvnw2Ks9l0jr0g31tQxEj_p1g9a23ambhG9qBtRbh_GepgiI2/pub?gid=0&single=true&output=csv&range=A9:D16" -o data.csv
          
          # Convert CSV to JSON
          python3 -c "
import pandas as pd
df = pd.read_csv('data.csv')
df.to_json('risk_age_group.json', orient='records')
"

      - name: Upload JSON
        uses: actions/upload-artifact@v2
        with:
          name: risk_age_group_json
          path: risk_age_group.json
